### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Pub4Game** [EconomyS/EconomyShop#2]
I really liked your economy with signs! Please bring them back, then what we have now is just awful, players don't understand where, how and what...

@onebone :cry:

**Comment by onebone** [comment]
Couldn't you make shops by touching signs?

**Comment by Pub4Game** [comment]
Look, I have this idea...

`/shop create 17:3 32 200`

And if I click a sign, then this sign appears in the text 

```
[SHOP]
32
200
Wood
```

And don't would be Item Displayer

**Comment by onebone** [comment]
You can hide item using
/shop create 17:3 32 200 -2

**Comment by Pub4Game** [comment]
Well, but the text on the plates, all the users have to write their own... It's very uncomfortable.

**Comment by onebone** [comment]
:+1:

**Comment by Pub4Game** [comment]
@onebone You're gorgeous as always!

Please make it and EconomySell
