### ISSUE TITLE
A bit of a silly thing

### ISSUE THREAD

**Issue by Pub4Game** [EconomyS/EconomyShop#9]
https://github.com/EconomyS/EconomyShop/blob/master/src/main/resources/config.yml#L6-L7

Let's say I created shop with sign. Then it broke... BUT it is not deleted from the configuration... you Have to go to configuration and there you need to delete the shop. Why is that? All my builders on the server just curses this thing.

Maybe you will do by DEFAULT - true? I think it will save from a lot of angry comments.

**Comment by Pub4Game** [comment]
@onebone

**Comment by onebone** [comment]
Agreed. I will make change tomorrow.
